docs/config-sample.yml, docs/ocp.md, roles/ocp/tasks/creds.yml, roles/ocp/templates/cloud-creds.j2, roles/ocp/templates/install-config.yaml.j2
Add GCP credentials creation on the controller machine during openshift cluster creation.
In case such credentials are missing, need to create them to prevent cloud platform login failure.
=> [OCP] - Add creation of gcp credentials

roles/acm/tasks/deploy.yml
When performing ACM Hib deploy, as part of the deploy flow, CSV that has been created after Subscription, should get "Succeeded" state phase.
Sometimes could be, that it might take a bit longer to create all the resources and states within a CSV.
Add a condition check to CSV install check task to avoid such failures.
=> [ACM] - Fix acm roles CSV check failure

roles/acm/tasks/deploy.yml
During deploy of the ACM Hub, two CatalogSources created:
- acm-custom-catalog
- mce-custom-catalog
Make sure to check both CatalogSource for readiness after creation.
=> [ACM] - Fix CatalogSource check during ACM deploy

README.md
Update install instructions within README to use tag instead of branch.
=> Update install reference to use the tag

roles/acm/tasks/deploy.yml
After creation of ACM Subscription, CSV resource created.
During the flow, we need to fetch the name of the CSV.
Creation of CSV resources and it's state could take some time.
Make sure to check for the states of CSV to prevent task failure.
=> [ACM] - Fix CSV name fetch failure

docs/config-sample.yml, docs/ocp.md, roles/ocp/defaults/main.yml, roles/ocp/tasks/creds.yml, roles/ocp/templates/cloud-creds.j2
Improve credentials structure in OCP role.
Current structure of credentials specify one single cluster per cloud platform.
```
aws:
aws_access_key_id: <value>
aws_secret_access_key: <value>
```
The new structure allows us to specify multiple credentials for the same cloud platform, so different clusters from the same platform are able to use separate credentials if needed.
```
- name: aws-creds
platform: aws
aws_access_key_id: <value>
aws_secret_access_key: <value>
```
=> [OCP] - Modify credentials structure in OCP role

roles/ocp/tasks/creds.yml, roles/ocp/tasks/process.yml, roles/ocp/templates/cloud-creds.j2, roles/ocp/templates/install-config.yaml.j2
When a creds file already exists, the role will append the new credentials to the end of this file. 
When there is no creds file, the role will create a new one. 
In addition fix the path to the cred_file.
=> Add a task appending to existing creds file

docs/cluster_login.md, roles/cluster_login/defaults/main.yml, roles/cluster_login/tasks/main.yml
The "cluster_login" role generates a token from the cluster for later use.
By default, cluster details taken from the first cluster within the "clusters_details.yml" file.
It's possible to define specific cluster to be used.
Update the var for that cluster to - cluster_login_name
=> [Cluster Login] - Update cluster login var name

docs/acm_import_cluster.md, docs/config-sample.yml, roles/acm_import_cluster/README.md, roles/acm_import_cluster/defaults/main.yml, roles/acm_import_cluster/tasks/handle_import_secret.yml, roles/acm_import_cluster/tasks/locate_kubeconfig_file.yml, roles/acm_import_cluster/tasks/main.yml, roles/acm_import_cluster/tasks/process_import.yml, roles/acm_import_cluster/templates/cloud-secret.yaml.j2, roles/acm_import_cluster/templates/clouds.yaml.j2, roles/acm_import_cluster/templates/klusterlet-addon-config.yaml.j2, roles/acm_import_cluster/templates/kubeconfig-secret.yaml.j2, roles/acm_import_cluster/templates/managed-cluster.yaml.j2, roles/acm_import_cluster/vars/main.yml
The new "acm_import_cluster" roles will allow to import / detach clusters deployed by using "ocp" or "managed_openshift" roles or manually.
=> Add new role - acm_import_cluster

roles/managed_openshift/tasks/clusters_dirs.yml
When managed openshift cluster being deployed, a state file with clusters connection details being created.
While clusters deleted, the entries removed from the state file. Finally, the state file should be deleted if it's empty.
=> [Managed Openshift] - Add state file removal

roles/acm_import_cluster/tasks/locate_kubeconfig_file.yml, roles/acm_import_cluster/vars/main.yml, roles/cluster_login/tasks/main.yml, roles/managed_openshift/tasks/aro/fetch_connection_details.yml, roles/managed_openshift/tasks/clusters_dirs.yml, roles/managed_openshift/tasks/main.yml, roles/managed_openshift/tasks/rosa/fetch_connection_details.yml, roles/managed_openshift/vars/main.yml, roles/ocp/defaults/main.yml, roles/ocp/tasks/fetch_details.yml, roles/ocp/tasks/main.yml, roles/ocp/vars/main.yml
Diring deployment of clusters by using an "ocp" or "managed_openshift" roles, a "cluster_details.yml" file was created.
Separate file for each role.
In order to ease the management and provide the ability to use any other deployed cluster as hub, combine the both files into one single file. The file will be generated under "logs" directory and will contain any cluster being deployed by "ocp" and/or "managed_openshift" role.
=> Combine cluster_details.yml file for all clusters

docs/acm.md, docs/config-sample.yml, roles/acm/defaults/main.yml, roles/acm/tasks/deploy.yml, roles/acm/tasks/destroy.yml, roles/acm/tasks/test_env_config.yml, roles/acm/templates/multiclusterhub.yaml.j2, roles/acm/templates/subscription.yaml.j2
Add a "downstream: true/false" parameter to control where ACM should be deployed from:
- Official RH registry
- Downstream (internal) testing registry
=> [ACM] - Add source deployment method to ACM role

roles/managed_openshift/tasks/clusters_dirs.yml, roles/managed_openshift/tasks/main.yml, roles/managed_openshift/tasks/prepare_clusters_list.yml, roles/ocp/tasks/main.yml, roles/ocp/tasks/prepare_clusters_list.yml, roles/ocp/tasks/process.yml
The "OCP" and "MANAGED_OPENSHIFT" roles have an identical variable - "clusters_list".
When executing the roles in one playbook execution, the "clusters_list" variables gets mixed and wrong items added to the list.
Separate the variables to become identical for each role.
=> Separate identical "clusters_list" variables

roles/acm_import_cluster/defaults/main.yml
In "acm_hive_cluster", the default variable "acm_import_clusters" is used to define the clusters that should be imported. But if this role is used in a general playbook that may need to skip the execution of the role, the definition of the variable with unexisting values may fail the execution of the entire playbook.
Comment out the default variable, so it will be defined only when explicitly used.
=> [ACM_HIVE_CLUSTER] - Comment out default var

roles/cluster_login/tasks/main.yml
The cluster_login role flow logins into the Openshift cluster in the following ways:
1) Looks for a "cluster_details.yml" file and takes from there the first
defined cluster or specific cluster defined by the user.
2) If the file does not exist, but login environment variables are
defined, use them.
The environment variables will take priority over cluster details file.
Currently, if cluster details file exists, but requested cluster entry is missing from it, even that environment variables defined, the flow will fail.
Modify the flow to make sure that if the cluster details file exists but missing the requested clsuter entry, but environment variable for connection are defined, move on and use the defined environment variables.
=> [CLUSTER_LOGIN] - Modify cluster login flow

roles/managed_openshift/tasks/roks/check_cluster.yml, roles/managed_openshift/tasks/roks/prerequisites.yml
Relocate ROKS login command in "managed_openshift" role to be able to gather account id.
=> [MANAGED_OPENSHIFT] - Relocate ROKS login command

docs/config-sample.yml, docs/managed_openshift.md, roles/managed_openshift/tasks/rosa/fetch_version.yml, roles/managed_openshift/tasks/rosa/process.yml
Modify ROSA cluster version selection for deployment. With the change, the user should be able to define the requested version to be deployed instead of searching for specific version and defining it prior the deployment.
In the new flow, the requested version defined by the user, for example
- 4.15, will be automatically searched across available versions and the last availabe version will be selected for ROSA cluster deployment.
=> [MANAGED_OPENSHIFT] - Modify ROSA cluster version deploy

docs/config-sample.yml, docs/managed_openshift.md, plugins/modules/azure_rm_openshiftmanagedclusterversion_info.py, roles/managed_openshift/tasks/aro/fetch_version.yml, roles/managed_openshift/tasks/aro/process.yml
Modify ARO cluster version selection for deployment. With the change, the user should be able to define the requested version to be deployed instead of searching for specific version and defining it prior the deployment.
In the new flow, the requested version defined by the user, for example
- 4.15, will be automatically searched across available versions and the last availabe version will be selected for ROSA cluster deployment.
A new azure collection module has been added to fetch available versions of openshift cluster to deploy.
A PR has been submitted to azure collection:
https://github.com/ansible-collections/azure/pull/1602
=> [MANAGED_OPENSHIFT] - Modify ARO cluster version deploy

roles/acm/defaults/main.yml, roles/acm/templates/multiclusterhub.yaml.j2
Modify ACM components enablement.
Instead of defining all the components for ACM for each deployment, modify it to define specific component to be enabled/disable if needed and the rest will take the default state of the ACM configuration.
=> [ACM] - Modify ACM components management

roles/acm_hive_cluster/defaults/main.yml, roles/managed_openshift/defaults/main.yml, roles/ocp/defaults/main.yml
Do not expose the default list of execution variables in roles to not create false execution parameters.
=> [Cross roles] - Do not expose default vars

roles/managed_openshift/tasks/rosa/process.yml
When creating multiple ROSA clusters, sometimes, cluster creation command may fail.
Add a retry to avoid the failure.
=> [MANAGED_OPENSHIFT] - Add retry to ROSA cluster creation task
